In [28]:
import pandas as pd

df = pd.read_csv("moleculenet/delaney-processed.csv")
df.head()

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
0,Amigdalin,-0.974,1,457.432,7,3,7,202.32,-0.77,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1,Fenfuram,-2.885,1,201.225,1,2,2,42.24,-3.30,Cc1occc1C(=O)Nc2ccccc2
2,citral,-2.579,1,152.237,0,0,4,17.07,-2.06,CC(C)=CCCC(C)=CC(=O)
3,Picene,-6.618,2,278.354,0,5,0,0.00,-7.87,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43
4,Thiophene,-2.232,2,84.143,0,1,0,0.00,-1.33,c1ccsc1

In [29]:
list(enumerate(df.columns))

[(0, 'Compound ID'),
 (1, 'ESOL predicted log solubility in mols per litre'),
 (2, 'Minimum Degree'),
 (3, 'Molecular Weight'),
 (4, 'Number of H-Bond Donors'),
 (5, 'Number of Rings'),
 (6, 'Number of Rotatable Bonds'),
 (7, 'Polar Surface Area'),
 (8, 'measured log solubility in mols per litre'),
 (9, 'smiles')]

In [30]:
df = df.iloc[:, [0, 9]]
df.columns = ["id", "desc"]
df["value"] = 0
df = df[["id", "value", "desc"]]
df

                  id  value                                               desc
0          Amigdalin      0  OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1           Fenfuram      0                             Cc1occc1C(=O)Nc2ccccc2
2             citral      0                               CC(C)=CCCC(C)=CC(=O)
3             Picene      0                 c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43
4          Thiophene      0                                            c1ccsc1
...              ...    ...                                                ...
1123       halothane      0                                   FC(F)(F)C(Cl)Br
1124          Oxamyl      0                          CNC(=O)ON=C(SC)C(=O)N(C)C
1125       Thiometon      0                                  CCSCCSP(=S)(OC)OC
1126  2-Methylbutane      0                                            CCC(C)C
1127        Stirofos      0              COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl

[1128 rows x 3 columns]

In [32]:
df.to_csv("moleculenet/new_processed_data.csv", index=False)